# Configuration file for creating a Conda Environment with dependencies needed for geocube.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: geocube
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- datacube
- gdal=2.4.*
- geopandas
- libgdal=2.4.*
- rasterio=1.0.*
- scipy
- rioxarray
