# Configuration file for creating a Conda Environment with dependencies needed for geocube.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: geocube
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- datacube
- geopandas
- rasterio
- scipy
- rioxarray
