# Configuration file for creating a Conda Environment with dependencies needed for geocube.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: geocube
channels:
- conda-forge
dependencies:
- python=3.10
- geopandas
- libgdal-netcdf
- libgdal-hdf4
- libgdal-hdf5
- odc-geo
- rasterio
- scipy
- rioxarray
